version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: projet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet
      MYSQL_USER: projet_user
      MYSQL_PASSWORD: projet_pwd
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: projet-java
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_NAME: projet
      DB_USER: projet_user
      DB_PASS: projet_pwd

volumes:
  mysql_data:
